In [1]:
cd ..

/home/jupyter/project/hse-masters-thesis-2026

In [2]:
import sys
import os

# project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
# if project_root not in sys.path:
#     sys.path.insert(0, project_root)
# os.chdir(project_root)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

from recommenders.utils.timer import Timer
from recommenders.models.deeprec.models.graphrec.lightgcn import LightGCN
from recommenders.models.deeprec.DataModel.ImplicitCF import ImplicitCF
from recommenders.datasets import movielens
from recommenders.datasets.python_splitters import python_stratified_split
from recommenders.evaluation.python_evaluation import map, ndcg_at_k, precision_at_k, recall_at_k
from recommenders.utils.constants import SEED as DEFAULT_SEED
from recommenders.models.deeprec.deeprec_utils import prepare_hparams
from recommenders.utils.notebook_utils import store_metadata

from tecd_retail_recsys.data import DataPreprocessor
from tecd_retail_recsys.metrics import calculate_metrics

print(f"System version: {sys.version}")
print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")
print(f"Tensorflow version: {tf.__version__}")

2026-04-07 21:06:07.196597: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-04-07 21:06:08.013659: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

System version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Pandas version: 2.3.3
Numpy version: 1.26.4
Tensorflow version: 2.12.0

In [3]:
TOP_K = 100
EPOCHS = 10
BATCH_SIZE = 1024

SEED = DEFAULT_SEED

yaml_file = "configs/lightgcn.yaml"
user_file = "models/lightgcn/user_embeddings.csv"
item_file = "models//lightgcn/item_embeddings.csv"

In [4]:
dp = DataPreprocessor(day_begin=1082, day_end=1308, val_days=20, test_days=20, min_user_interactions=1, min_item_interactions=20)
train_df, val_df, test_df = dp.preprocess()
train_df.rename(columns={'user_id': 'userID', 'item_id': 'itemID'}, inplace=True)
train_df['rating'] = 1.0
val_df.rename(columns={'user_id': 'userID', 'item_id': 'itemID'}, inplace=True)
val_df['rating'] = 1.0

Starting data preprocessing...
Loading events from t_ecd_small_partial/dataset/small/retail/events
Loaded 267,043,972 total events
Loading items data from t_ecd_small_partial/dataset/small/retail/items.pq
Loaded 250,171 items with features: ['item_id', 'item_brand_id', 'item_category', 'item_subcategory', 'item_price', 'item_embedding']
Merged item features. Data shape: (267043972, 12)

IOStream.flush timed out

Filtered to 3,852,145 events with action_type='added_to_cart'
After filtering (min_user_interactions=1, min_item_interactions=20): 3,327,057 events, 84,830 users, 32,095 items
Created mappings: 84830 users, 32095 items
Temporal split - Train: days < 1269 (922,368 events), Val: days 1269-1288 (232,900 events), Test: days >= 1289 (227,959 events)
Users in each part (train, val, test) - 7422

In [5]:
data = ImplicitCF(train=train_df, test=val_df, seed=SEED)

In [6]:
hparams = prepare_hparams(yaml_file,
                        #   n_layers=3,
                        #   batch_size=BATCH_SIZE,
                        #   epochs=EPOCHS,
                        #   learning_rate=0.005,
                        #   eval_epoch=5,
                          top_k=TOP_K
                         )

In [7]:
for param in ['n_layers', 'embed_size', 'batch_size', 'epochs', 'learning_rate', 'decay', 'eval_epoch', 'top_k']:
    print(param, hparams.__dict__[param])

n_layers 3
embed_size 256
batch_size 1024
epochs 30
learning_rate 0.002
decay 0.0001
eval_epoch 5
top_k 100

In [8]:
model = LightGCN(hparams, data, seed=SEED)

Already create adjacency matrix.
Already normalize adjacency matrix.
Using xavier initialization.

2026-04-07 21:10:44.384520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79262 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:81:00.0, compute capability: 8.0
2026-04-07 21:10:44.399716: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled

In [ ]:
with Timer() as train_time:
    model.fit()

print("Took {} seconds for training.".format(train_time.interval))

Epoch 1 (train)25.8s: train loss = 0.41444 = (mf)0.41377 + (embed)0.00066
Epoch 2 (train)24.5s: train loss = 0.28245 = (mf)0.28087 + (embed)0.00157
Epoch 3 (train)24.5s: train loss = 0.23842 = (mf)0.23612 + (embed)0.00230
Epoch 4 (train)24.5s: train loss = 0.21501 = (mf)0.21209 + (embed)0.00292

2026-04-07 21:12:49.246593: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.

Epoch 5 (train)24.5s + (eval)7.8s: train loss = 0.19368 = (mf)0.19012 + (embed)0.00356, recall = 0.06488, ndcg = 0.06639, precision = 0.01977, map = 0.01271
Epoch 6 (train)24.6s: train loss = 0.17244 = (mf)0.16818 + (embed)0.00426
Epoch 7 (train)24.5s: train loss = 0.15278 = (mf)0.14777 + (embed)0.00502
Epoch 8 (train)24.6s: train loss = 0.13358 = (mf)0.12774 + (embed)0.00583
Epoch 9 (train)24.5s: train loss = 0.11704 = (mf)0.11037 + (embed)0.00667
Epoch 10 (train)24.5s + (eval)7.7s: train loss = 0.10241 = (mf)0.09490 + (embed)0.00750, recall = 0.06362, ndcg = 0.06559, precision = 0.01970, map = 0.01241
Epoch 11 (train)24.5s: train loss = 0.08952 = (mf)0.08120 + (embed)0.00833
Epoch 12 (train)24.5s: train loss = 0.07985 = (mf)0.07074 + (embed)0.00911
Epoch 13 (train)24.6s: train loss = 0.07120 = (mf)0.06134 + (embed)0.00986
Epoch 14 (train)24.5s: train loss = 0.06384 = (mf)0.05328 + (embed)0.01056
Epoch 15 (train)24.5s + (eval)8.0s: train loss = 0.05835 = (mf)0.04713 + (embed)0.01122, recall = 0.06396, ndcg = 0.06475, precision = 0.01954, map = 0.01204
Epoch 16 (train)24.5s: train loss = 0.05370 = (mf)0.04190 + (embed)0.01180
Epoch 17 (train)24.5s: train loss = 0.04943 = (mf)0.03708 + (embed)0.01236
Epoch 18 (train)24.5s: train loss = 0.04611 = (mf)0.03325 + (embed)0.01286
Epoch 19 (train)24.4s: train loss = 0.04344 = (mf)0.03012 + (embed)0.01332
Epoch 20 (train)24.5s + (eval)7.2s: train loss = 0.04096 = (mf)0.02722 + (embed)0.01374, recall = 0.06266, ndcg = 0.06412, precision = 0.01934, map = 0.01194
Epoch 21 (train)24.6s: train loss = 0.03911 = (mf)0.02500 + (embed)0.01410
Epoch 22 (train)24.6s: train loss = 0.03724 = (mf)0.02280 + (embed)0.01443
Epoch 23 (train)24.6s: train loss = 0.03598 = (mf)0.02125 + (embed)0.01473
Epoch 24 (train)24.6s: train loss = 0.03504 = (mf)0.02003 + (embed)0.01500
Epoch 25 (train)24.6s + (eval)7.6s: train loss = 0.03382 = (mf)0.01858 + (embed)0.01524, recall = 0.06153, ndcg = 0.06272, precision = 0.01894, map = 0.01160
Epoch 26 (train)24.6s: train loss = 0.03285 = (mf)0.01739 + (embed)0.01546
Epoch 27 (train)24.5s: train loss = 0.03202 = (mf)0.01637 + (embed)0.01565
Epoch 29 (train)24.6s: train loss = 0.03082 = (mf)0.01484 + (embed)0.01598

In [17]:
checkpoint_path = "models/lightgcn/model"
model.saver.save(model.sess, checkpoint_path)

'models/lightgcn/model'

In [25]:
topk_scores = model.recommend_k_items(train_df, top_k=TOP_K, remove_seen=False)
topk_scores.head()

   userID  itemID  prediction
0   72712   18598   11.160798
1   72712    5857   10.090414
2   72712    8306    9.929247
3   72712   24899    9.652122
4   72712   18039    9.343480

In [26]:
recs = topk_scores.sort_values(by=['userID', 'prediction'], ascending=[True,False]).groupby('userID', as_index=False)['itemID'].apply(list)
recs.head()

   userID                                             itemID
0      12  [11868, 19043, 22423, 28085, 10505, 31361, 170...
1      15  [26588, 11816, 9223, 30204, 15937, 7410, 8836,...
2      23  [24216, 30325, 21002, 4417, 18598, 25368, 1348...
3      30  [18598, 8306, 9228, 5857, 27511, 16356, 1770, ...
4      39  [8928, 29076, 28862, 31314, 17344, 23624, 1572...

In [27]:
eval_map = map(val_df, topk_scores, k=TOP_K)
eval_ndcg = ndcg_at_k(val_df, topk_scores, k=TOP_K)
eval_precision = precision_at_k(val_df, topk_scores, k=TOP_K)
eval_recall = recall_at_k(val_df, topk_scores, k=TOP_K)

print("MAP:\t%f" % eval_map,
      "NDCG:\t%f" % eval_ndcg,
      "Precision@K:\t%f" % eval_precision,
      "Recall@K:\t%f" % eval_recall, sep='\n')

MAP:	0.050843
NDCG:	0.217303
Precision@K:	0.063161
Recall@K:	0.192583

In [28]:
model.infer_embedding(user_file, item_file)

In [29]:
train_df.rename(columns={'userID': 'user_id', 'itemID': 'item_id'}, inplace=True)
val_df.rename(columns={'userID': 'user_id', 'itemID': 'item_id'}, inplace=True)
joined = dp.get_grouped_data(train_df, val_df, test_df)
joined['train_val_interactions'] = joined['train_interactions'] + joined['val_interactions']
print(joined.shape)

joined = joined.merge(recs, left_on='user_id', right_on='userID').rename(columns={'itemID': 'lightgcn_recs'})
calculate_metrics(joined, train_col='train_interactions', gt_col='val_interactions', model_preds='lightgcn_recs', verbose=True)

(7422, 5)
[Metrics debug] resolved gt_col='val_interactions' item_id_index=0
[Metrics debug] ratings_true shape: (232900, 3) ratings_pred shape: (742200, 3)
  ratings_true dtypes: {'user_id': dtype('int64'), 'item_id': dtype('int64')}
  ratings_pred dtypes: {'user_id': dtype('int64'), 'item_id': dtype('int64')}
  user_id=12 gt_count=23 pred_count=100 overlap=7
  user_id=15 gt_count=4 pred_count=100 overlap=0
    [ID spaces] gt sample=[9711, 17337, 18236, 29069] range=[9711, 29069] | rec sample=[237, 976, 1247, 1311, 1770] range=[237, 31596]
  user_id=23 gt_count=48 pred_count=100 overlap=15

At k=10:
  MAP@10       = 0.1040
  NDCG@10      = 0.2699
  Precision@10 = 0.1404
  Recall@10    = 0.0462

At k=100:
  MAP@100       = 0.0522
  NDCG@100      = 0.2173
  Precision@100 = 0.0632
  Recall@100    = 0.1926

Other Metrics:
  MRR                 = 0.2513
  Catalog Coverage    = 0.9932
  Diversity     = 0.9968  [0=same recs for all, 1=unique recs]
  Novelty             = 0.7958
  Serendipity         = 0.0269

{'MAP@10': 0.1040293115122732,
 'NDCG@10': 0.26987289886594124,
 'Precision@10': 0.14040689841013201,
 'Recall@10': 0.04615138757500724,
 'MAP@100': 0.05220521898130625,
 'NDCG@100': 0.2173033189305343,
 'Precision@100': 0.06316087308003233,
 'Recall@100': 0.1925827913946597,
 'MRR': 0.2512924897467249,
 'Catalog_Coverage': 0.9931622859293645,
 'Diversity': 0.9968418393127843,
 'Novelty': 0.7958078781445486,
 'Serendipity': 0.026876938404941608}

<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            font-family: Arial, sans-serif;
            margin: 20px 0;
        }
        th {
            background-color: #4CAF50;
            color: white;
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
        }
        td {
            padding: 10px;
            border: 1px solid #ddd;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        .best {
            background-color: #c8e6c9 !important;
            font-weight: bold;
        }
        .worst {
            background-color: #ffcdd2 !important;
        }
    </style>
</head>
<body>
    <h2>LightGCN: эксперименты</h2>
    <table>
        <thead>
            <tr>
                <th>Номер эксперимента</th>
                <th>embed_size</th>
                <th>n_layers</th>
                <th>decay</th>
                <th>epochs</th>
                <th>learning_rate</th>
                <th>batch_size</th>
                <th>NDCG@100</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>64</td>
                <td>3</td>
                <td>0.0001</td>
                <td>10</td>
                <td>0.005</td>
                <td>1024</td>
                <td>0.161162</td>
            </tr>
            <tr>
                <td>2</td>
                <td>256</td>
                <td>3</td>
                <td>0.001</td>
                <td>10</td>
                <td>0.005</td>
                <td>1024</td>
                <td>0.188174</td>
            </tr>
            <tr class="worst">
                <td>3</td>
                <td>512</td>
                <td>4</td>
                <td>0.00005</td>
                <td>10</td>
                <td>0.002</td>
                <td>1024</td>
                <td>0.173303</td>
            </tr>
            <tr>
                <td>4</td>
                <td>384</td>
                <td>3</td>
                <td>0.0002</td>
                <td>10</td>
                <td>0.002</td>
                <td>1024</td>
                <td>0.176823</td>
            </tr>
            <tr class="best">
                <td>5</td>
                <td>256</td>
                <td>3</td>
                <td>0.0001</td>
                <td>30</td>
                <td>0.002</td>
                <td>1024</td>
                <td><strong>0.218600</strong></td>
            </tr>
        </tbody>
    </table>
</body>
</html>


`Наилучшая конфигурация смогли добиться NDCG@100 = 0.2186`

### Инференс на тесте

In [42]:
train_val_df = pd.concat([train_df, val_df])
train_val_df.rename(columns={'user_id': 'userID', 'item_id': 'itemID'}, inplace=True)
test_df.rename(columns={'user_id': 'userID', 'item_id': 'itemID'}, inplace=True)
train_val_df['rating'] = 1.0
test_df['rating'] = 1.0

In [43]:
data = ImplicitCF(train=train_val_df, test=test_df, seed=SEED)

In [44]:
model = LightGCN(hparams, data, seed=SEED)

Already create adjacency matrix.
Already normalize adjacency matrix.
Using xavier initialization.

2026-04-07 21:36:26.379217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79262 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-80GB, pci bus id: 0000:81:00.0, compute capability: 8.0

In [45]:
with Timer() as train_time:
    model.fit()

print("Took {} seconds for training.".format(train_time.interval))

Epoch 1 (train)37.0s: train loss = 0.42578 = (mf)0.42513 + (embed)0.00065
Epoch 2 (train)36.5s: train loss = 0.31268 = (mf)0.31117 + (embed)0.00151
Epoch 3 (train)36.5s: train loss = 0.26939 = (mf)0.26714 + (embed)0.00225
Epoch 4 (train)36.4s: train loss = 0.24594 = (mf)0.24303 + (embed)0.00290
Epoch 5 (train)36.5s + (eval)9.4s: train loss = 0.22341 = (mf)0.21981 + (embed)0.00360, recall = 0.06128, ndcg = 0.05855, precision = 0.01770, map = 0.01082
Epoch 6 (train)36.5s: train loss = 0.19993 = (mf)0.19550 + (embed)0.00443
Epoch 7 (train)36.5s: train loss = 0.17597 = (mf)0.17060 + (embed)0.00537
Epoch 8 (train)36.5s: train loss = 0.15251 = (mf)0.14611 + (embed)0.00640
Epoch 9 (train)36.5s: train loss = 0.13230 = (mf)0.12483 + (embed)0.00747
Epoch 10 (train)36.5s + (eval)8.8s: train loss = 0.11546 = (mf)0.10692 + (embed)0.00855, recall = 0.06282, ndcg = 0.05938, precision = 0.01824, map = 0.01075
Epoch 11 (train)36.5s: train loss = 0.10074 = (mf)0.09113 + (embed)0.00961
Epoch 12 (train)36.5s: train loss = 0.08856 = (mf)0.07794 + (embed)0.01061
Epoch 13 (train)36.6s: train loss = 0.07952 = (mf)0.06795 + (embed)0.01157
Epoch 14 (train)36.6s: train loss = 0.07166 = (mf)0.05921 + (embed)0.01245
Epoch 15 (train)36.4s + (eval)8.5s: train loss = 0.06543 = (mf)0.05217 + (embed)0.01326, recall = 0.06297, ndcg = 0.05898, precision = 0.01819, map = 0.01058
Epoch 16 (train)36.5s: train loss = 0.06022 = (mf)0.04620 + (embed)0.01401
Epoch 17 (train)36.5s: train loss = 0.05590 = (mf)0.04121 + (embed)0.01469
Epoch 18 (train)36.5s: train loss = 0.05231 = (mf)0.03700 + (embed)0.01531
Epoch 19 (train)36.5s: train loss = 0.04955 = (mf)0.03369 + (embed)0.01586
Epoch 20 (train)36.5s + (eval)9.3s: train loss = 0.04694 = (mf)0.03058 + (embed)0.01637, recall = 0.06204, ndcg = 0.05836, precision = 0.01790, map = 0.01046
Epoch 21 (train)36.5s: train loss = 0.04505 = (mf)0.02825 + (embed)0.01681
Epoch 22 (train)36.5s: train loss = 0.04339 = (mf)0.02618 + (embed)0.01721
Epoch 23 (train)36.6s: train loss = 0.04172 = (mf)0.02415 + (embed)0.01757
Epoch 24 (train)36.5s: train loss = 0.04063 = (mf)0.02274 + (embed)0.01789
Epoch 25 (train)36.5s + (eval)9.0s: train loss = 0.03949 = (mf)0.02131 + (embed)0.01817, recall = 0.06081, ndcg = 0.05690, precision = 0.01748, map = 0.01026
Epoch 26 (train)36.5s: train loss = 0.03868 = (mf)0.02025 + (embed)0.01843
Epoch 27 (train)36.5s: train loss = 0.03772 = (mf)0.01906 + (embed)0.01866
Epoch 28 (train)36.6s: train loss = 0.03685 = (mf)0.01799 + (embed)0.01886
Epoch 29 (train)36.5s: train loss = 0.03634 = (mf)0.01731 + (embed)0.01903
Epoch 30 (train)36.4s + (eval)9.0s: train loss = 0.03563 = (mf)0.01645 + (embed)0.01919, recall = 0.06082, ndcg = 0.05599, precision = 0.01740, map = 0.00977
Took 1149.2578101630006 seconds for training.

In [46]:
checkpoint_path = "models_test/lightgcn/model"
model.saver.save(model.sess, checkpoint_path)

'models_test/lightgcn/model'

In [47]:
topk_scores = model.recommend_k_items(train_val_df, top_k=TOP_K, remove_seen=False)
topk_scores.head()

   userID  itemID  prediction
0   72712   18598   10.987949
1   72712    5857   10.860213
2   72712   17088    9.389510
3   72712    1899    9.291262
4   72712   18039    9.143493

In [48]:
recs = topk_scores.sort_values(by=['userID', 'prediction'], ascending=[True,False]).groupby('userID', as_index=False)['itemID'].apply(list)
recs.head()

   userID                                             itemID
0      12  [15220, 10189, 1812, 523, 10505, 6272, 26978, ...
1      15  [20448, 26588, 1247, 30204, 18598, 24673, 1004...
2      23  [18598, 29296, 18969, 13859, 15539, 16646, 269...
3      30  [28862, 27511, 25995, 12782, 18598, 1770, 8928...
4      39  [17344, 8928, 25995, 28862, 29076, 15603, 1083...

In [49]:
train_val_df.rename(columns={'userID': 'user_id', 'itemID': 'item_id'}, inplace=True)
test_df.rename(columns={'userID': 'user_id', 'itemID': 'item_id'}, inplace=True)
joined = dp.get_grouped_data(train_df, val_df, test_df)
joined['train_val_interactions'] = joined['train_interactions'] + joined['val_interactions']
print(joined.shape)

joined = joined.merge(recs, left_on='user_id', right_on='userID').rename(columns={'itemID': 'lightgcn_recs'})
calculate_metrics(joined, train_col='train_val_interactions', gt_col='test_interactions', model_preds='lightgcn_recs', verbose=True)

(7422, 5)
[Metrics debug] resolved gt_col='test_interactions' item_id_index=0
[Metrics debug] ratings_true shape: (227959, 3) ratings_pred shape: (742200, 3)
  ratings_true dtypes: {'user_id': dtype('int64'), 'item_id': dtype('int64')}
  ratings_pred dtypes: {'user_id': dtype('int64'), 'item_id': dtype('int64')}
  user_id=12 gt_count=10 pred_count=100 overlap=3
  user_id=15 gt_count=54 pred_count=100 overlap=2
  user_id=23 gt_count=38 pred_count=100 overlap=14

At k=10:
  MAP@10       = 0.1005
  NDCG@10      = 0.2589
  Precision@10 = 0.1318
  Recall@10    = 0.0458

At k=100:
  MAP@100       = 0.0526
  NDCG@100      = 0.2222
  Precision@100 = 0.0640
  Recall@100    = 0.2082

Other Metrics:
  MRR                 = 0.2459
  Catalog Coverage    = 0.9949
  Diversity     = 0.9969  [0=same recs for all, 1=unique recs]
  Novelty             = 0.7870
  Serendipity         = 0.0270

{'MAP@10': 0.10045665525734031,
 'NDCG@10': 0.2588967878537313,
 'Precision@10': 0.1317838857450822,
 'Recall@10': 0.04582724138899301,
 'MAP@100': 0.052627716204664915,
 'NDCG@100': 0.22219075482049838,
 'Precision@100': 0.06398949070331447,
 'Recall@100': 0.2081616588266326,
 'MRR': 0.2458539171704546,
 'Catalog_Coverage': 0.9948836338678481,
 'Diversity': 0.9968642207588586,
 'Novelty': 0.7869638585273092,
 'Serendipity': 0.02698304665639602}

In [50]:
from tecd_retail_recsys.utils import calculate_avg_prices, calculate_overall_avg_price, get_avg_recs_price, get_item_to_price
item_to_price = get_item_to_price(dp)
avg_recs_price_test = get_avg_recs_price(joined, item_to_price, 'lightgcn_recs')
print(f'Средняя цена рекомендаций модели LightGCN на тесте: {avg_recs_price_test:.2f}')

Средняя цена рекомендаций модели LightGCN на тесте: -3.98